// This is template generated by CPCLI [https://github.com/ericliclair/cpcli]
// problem link [https://cses.fi/problemset/task/1618]

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef vector<int> vi;
typedef vector<vector<int>> vvi;

int trailingZeroes(ll n)
{
    // number of trailing zeroes in n = count of 5's as a factor of n
    int count = 0;

    for (int i = 5; i <= n; i *= 5)
    {
        count += n / i;
    }

    return count;
}

int main()
{
    ll n;
    cin >> n;
    cout << trailingZeroes(n) << endl;
    return 0;
}