// This is template generated by CPCLI [https://github.com/ericliclair/cpcli]
// problem link [https://cses.fi/problemset/task/1083]

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef vector<int> vi;
typedef vector<vector<int>> vvi;

int main()
{
    int n;
    cin >> n;
    int counter = 0;
    for (int i = 1; i <= n - 1; i++)
    {
        int input;
        cin >> input;
        counter = counter ^ i ^ input;
    }

    cout << (counter ^ n) << endl;
    return 0;
}