// This is template generated by CPCLI [https://github.com/ericliclair/cpcli]
// problem link [https://cses.fi/problemset/task/1071]

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef vector<int> vi;
typedef vector<vector<int>> vvi;

// column x, row y
long long int spiral(long long int x, long long int y)
{
    if (y > x || (y == x && y))
    {
        if (y % 2 == 0)
        {
            // y is even -> y2 - (x - 1)
            return (y * y) - (x - 1);
        }
        else
        {
            // y is odd -> (y-1)2 + (x - 1)
            return (y - 1) * (y - 1) + 1 + (x - 1);
        }
    }
    else
    {
        if (x % 2 == 0)
        {
            // x is even -> (x-1)2 + (y-1)
            return (x - 1) * (x - 1) + 1 + (y - 1);
        }
        else
        {
            // x is odd -> x2 - (y - 1)
            return (x * x) - (y - 1);
        }
    }
}

int main()
{
    long long int t;
    cin >> t;
    while (t--)
    {
        // column x, row y
        long long int y, x;
        cin >> y >> x;

        cout << spiral(x, y) << endl;
    }
}