// This is template generated by CPCLI [https://github.com/ericliclair/cpcli]

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef vector<int> vi;
typedef vector<vector<int>> vvi;

float volumeFractions(vi &drinks)
{
    int sum = 0;
    for (const int &p : drinks)
    {
        sum += p;
    }

    return (float)sum / drinks.size();
}

int main()
{
    int n;
    cin >> n;

    vi drinks(n);
    for (int i = 0; i < n; i++)
    {
        cin >> drinks[i];
    }
    cout << volumeFractions(drinks) << endl;
    return 0;
}