// This is template generated by CPCLI [https://github.com/ericliclair/cpcli]
// problem link [https://leetcode.com/problems/merge-two-sorted-lists/]

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef vector<int> vi;
typedef vector<vector<int>> vvi;

struct ListNode
{
    int val;
    ListNode *next;
    ListNode() : val(0), next(nullptr) {}
    ListNode(int x) : val(x), next(nullptr) {}
    ListNode(int x, ListNode *next) : val(x), next(next) {}
};

class Solution
{
public:
    ListNode *mergeTwoLists(ListNode *list1, ListNode *list2)
    {
        ListNode *head = new ListNode(-1);
        ListNode *ptr = head;

        while (list1 && list2)
        {
            if (list1->val < list2->val)
            {
                ptr->next = list1;
                ptr = ptr->next;
                list1 = list1->next;
            }
            else
            {
                ptr->next = list2;
                ptr = ptr->next;
                list2 = list2->next;
            }
        }

        if (list1)
            ptr->next = list1;
        if (list2)
            ptr->next = list2;

        return head->next;
    }
};
int main()
{
    cout << "Hey champ!";
    return 0;
}