// This is template generated by CPCLI [https://github.com/ericliclair/cpcli]
// problem link [https://leetcode.com/problems/maximum-subarray/]

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef vector<int> vi;
typedef vector<vector<int>> vvi;

class Solution
{
public:
    int maxSubArray(vector<int> &nums)
    {
        int meh = 0;
        int msf = nums[0];

        for (int i = 0; i < nums.size(); i++)
        {
            meh += nums[i];
            msf = max(msf, meh);
            meh = max(meh, 0);
        }
        return msf;
    }
};

int main()
{
    int n;
    cin >> n;
    vi nums(n);
    for (int i = 0; i < n; i++)
    {
        cin >> nums[i];
    }

    cout << Solution().maxSubArray(nums) << endl;
}