// This is template generated by CPCLI [https://github.com/ericliclair/cpcli]
// problem link [https://cses.fi/problemset/task/1072]

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef vector<int> vi;
typedef vector<vector<int>> vvi;

ll numberOfPossibleWays(int n)
{
    // total number of ways to place 2 knights - number of ways threatens each other

    ll waysToThreaten = 2 * 2 * (n - 1) * (n - 2);
    ll totalNumberOfWays = pow(n, 2) * (pow(n, 2) - 1) / 2;

    return totalNumberOfWays - waysToThreaten;
}

int main()
{
    int n;
    cin >> n;

    for (int i = 1; i <= n; i++)
    {
        cout << numberOfPossibleWays(i) << endl;
    }
    return 0;
}