// This is template generated by CPCLI [https://github.com/ericliclair/cpcli]
// problem link [https://codeforces.com/problemset/problem/151/A]

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef vector<int> vi;
typedef vector<vector<int>> vvi;

int main()
{
    int n, k, l, c, d, p, nl, np;

    cin >> n >> k >> l >> c >> d >> p >> nl >> np;
    int ans = min({((k * l) / (n * nl)), ((c * d) / n), (p / (np * n))});
    cout << ans << endl;
    return 0;
}