// This is template generated by CPCLI [https://github.com/ericliclair/cpcli]
// problem link [https://codeforces.com/problemset/problem/228/A]
#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef vector<int> vi;
typedef vector<vector<int>> vvi;

int main()
{
    int count = 0;
    map<int, bool> visited;
    for (int i = 0; i < 4; i++)
    {
        int s;
        cin >> s;
        if (visited.find(s) != visited.end()) // alreadyVisited
        {
            count++;
        }
        else
        {
            visited[s] = true;
        }
    }

    cout << count << endl;
}