// This is template generated by CPCLI [https://github.com/ericliclair/cpcli]
// problem link [https://leetcode.com/problems/set-matrix-zeroes/]

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef vector<int> vi;
typedef vector<vector<int>> vvi;

class Solution
{

    void makeZero(vvi &matrix)
    {
        vi row_zero(matrix.size());
        vi col_zero(matrix[0].size());

        for (int i = 0; i < matrix.size(); i++)
        {
            for (int j = 0; j < matrix[0].size(); j++)
            {
                if (matrix[i][j] == 0)
                {
                    row_zero[i] = 1;
                    col_zero[j] = 1;
                }
            }
        }

        // make all rows corresponding to a zero as zero
        for (int i = 0; i < matrix.size(); i++)
        {
            if (row_zero[i] == 1)
            {
                for (int j = 0; j < matrix[0].size(); j++)
                {
                    matrix[i][j] = 0;
                }
            }
        }

        // make all cols corresponding to a zero as zero
        for (int i = 0; i < matrix[0].size(); i++)
        {
            if (col_zero[i] == 1)
            {
                for (int j = 0; j < matrix.size(); j++)
                {
                    matrix[j][i] = 0;
                }
            }
        }
    }

public:
    void setZeroes(vector<vector<int>> &matrix)
    {
        makeZero(matrix);
    }
};

int main()
{
    cout << "Hey champ!";
    return 0;
}