// This is template generated by CPCLI [https://github.com/ericliclair/cpcli]
// problem link [https://cses.fi/problemset/task/1094]
#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef vector<int> vi;
typedef vector<vector<int>> vvi;

int main()
{
    int n;
    cin >> n;
    vector<ll> nums(n);
    for (int i = 0; i < n; i++)
    {
        cin >> nums[i];
    }
    ll moves = 0;
    for (int i = 1; i < n; i++)
    {
        ll diff = nums[i] - nums[i - 1];
        // 3 2
        if (diff < 0)
        {
            moves += abs(diff);
            nums[i] = nums[i - 1];
        }
    }

    cout << moves;
}