// This is template generated by CPCLI [https://github.com/ericliclair/cpcli]

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef vector<int> vi;
typedef vector<vector<int>> vvi;

void transpose(vvi &matrix)
{
    for (int i = 0; i < matrix.size(); i++)
    {
        for (int j = 0; j < i; j++)
        {
            swap(matrix[i][j], matrix[j][i]);
        }
    }
}

void reverseRow(vi &row)
{
    int s = 0;
    int e = row.size() - 1;

    while (s < e)
    {
        swap(row[s++], row[e--]);
    }
}

void rotate90_clockwise(vvi &matrix)
{
    // transpose and reverse each row
    transpose(matrix);
    for (vi &row : matrix)
    {
        reverseRow(row);
    }
}

int main()
{
    int n;
    cin >> n;
    vvi matrix;
    for (int i = 0; i < n; i++)
    {
        for (int j = 0; j < n; j++)
        {
            cin >> matrix[i][j];
        }
    }

    rotate90_clockwise(matrix);
}