// This is template generated by CPCLI [https://github.com/ericliclair/cpcli]
// problem link [https://codeforces.com/problemset/problem/236/A]

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef vector<int> vi;
typedef vector<vector<int>> vvi;

class Persona
{
    string username;
    string verdict;

    void computeVerdict()
    {
        vi char_count(26);
        for (const char &ch : username)
        {
            char_count[ch - 'a'] = 1;
        }

        int count = 0;
        for (const int &c : char_count)
        {
            count += c;
        }

        this->verdict = (count % 2 == 0) ? "CHAT WITH HER!" : "IGNORE HIM!";
    }

public:
    Persona(string _s)
    {
        this->username = _s;
        this->computeVerdict();
    }

    string getVerdict()
    {
        return this->verdict;
    }
};

int main()
{
    string s;
    cin >> s;
    Persona p = Persona(s);
    cout << p.getVerdict() << endl;
    return 0;
}