// This is template generated by CPCLI [https://github.com/ericliclair/cpcli]
// problem link [https://codeforces.com/problemset/problem/141/A]

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef vector<int> vi;
typedef vector<vector<int>> vvi;

int main()
{
    string s1, s2, s3;
    cin >> s1 >> s2 >> s3;

    vi count(26);
    for (const char &ch : s1)
    {
        count[ch - 'A']++;
    }
    for (const char &ch : s2)
    {
        count[ch - 'A']++;
    }

    for (const char &ch : s3)
    {
        count[ch - 'A']--;
    }

    for (const int &n : count)
    {
        if (n != 0)
        {
            cout << "NO";
            return 0;
        }
    }
    cout << "YES";
    return 0;
}