// This is template generated by CPCLI [https://github.com/ericliclair/cpcli]
// problem link [https://leetcode.com/problems/sort-colors/]

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef vector<int> vi;
typedef vector<vector<int>> vvi;

class Solution
{
public:
    void sortColors(vector<int> &nums)
    {
        int pivot = 1;
        int p = 0;
        int s = 0;
        int e = nums.size() - 1;
        while (p <= e)
        {
            if (nums[p] < pivot) // 0
            {
                swap(nums[s], nums[p]);
                s++;
                p++;
            }
            else if (nums[p] > pivot) // 2
            {
                swap(nums[e], nums[p]);
                e--;
            }
            else
            { // 1
                p++;
            }
        }
    }
};

int main()
{
    int n;
    cin >> n;
    vi colors(n);

    for (int i = 0; i < n; i++)
    {
        cin >> colors[i];
    }

    Solution().sortColors(colors);

    for (auto it : colors)
    {
        cout << it << " ";
    }
    cout << endl;
    return 0;
}