// This is template generated by CPCLI [https://github.com/ericliclair/cpcli]

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef vector<int> vi;
typedef vector<vector<int>> vvi;

int main()
{
    int n;
    cin >> n;
    int countLeft = 0;
    int countRight = 0;
    int k = n;
    while (n--)
    {
        int l, r;
        cin >> l >> r;
        countLeft += l;
        countRight += r;
    }

    int seconds = min(countLeft, k - countLeft) + min(countRight, k - countRight);
    cout << seconds;
    return 0;
}