// This is template generated by CPCLI [https://github.com/ericliclair/cpcli]
// problem link [https://www.interviewbit.com/problems/subarray-with-given-xor/]

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef vector<int> vi;
typedef vector<vector<int>> vvi;

int main()
{
    cout << "Hey champ!";
    return 0;
}