// This is template generated by CPCLI [https://github.com/ericliclair/cpcli]
// problem link [https://leetcode.com/problems/merge-sorted-array/]

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef vector<int> vi;
typedef vector<vector<int>> vvi;

class Solution
{
public:
    void merge(vector<int> &nums1, int m, vector<int> &nums2, int n)
    {
        int k = m + n - 1;
        m--;
        n--;

        while (m >= 0 && n >= 0)
        {
            if (nums1[m] < nums2[n])
            {
                nums1[k--] = nums1[m--];
            }
            else if (nums1[m] > nums2[n])
            {
                nums1[k--] = nums2[n--];
            }
            else
            {
                nums1[k--] = nums1[m--];
                nums1[k--] = nums2[n--];
            }
        }

        while (m >= 0)
        {
            nums1[k--] = nums1[m--];
        }

        while (n >= 0)
        {
            nums1[k--] = nums1[n--];
        }
    }
};

int main()
{
    cout << "Hey champ!";
    return 0;
}