// This is template generated by CPCLI [https://github.com/ericliclair/cpcli]
// problem link [https://codeforces.com/problemset/problem/339/A]

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef vector<int> vi;
typedef vector<vector<int>> vvi;

string formatS(string s)
{
    vi num_count(3); // 1 2 3
    string ans = "";
    for (auto ch : s)
    {
        if (ch == '1')
        {
            num_count[0]++;
        }
        if (ch == '2')
        {
            num_count[1]++;
        }
        if (ch == '3')
        {
            num_count[2]++;
        }
    }

    for (int i = 0; i < num_count.size(); i++)
    {
        int count = num_count[i];
        while (count--)
        {
            ans += '1' + i;
            ans += '+';
        }
    }
    ans.pop_back();
    return ans;
}

int main()
{
    string s;
    cin >> s;
    cout << formatS(s);
    return 0;
}