// This is template generated by CPCLI [https://github.com/ericliclair/cpcli]

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef vector<int> vi;
typedef vector<vector<int>> vvi;

class Solution
{
public:
    vector<int> twoSum(vector<int> &nums, int target)
    {
        map<int, int> store;

        for (int i = 0; i < nums.size(); i++)
        {
            int n = nums[i];
            if (store.find(target - n) != store.end())
                return {i, store[target - n]};
            else
                store[n] = i;
        }
        return {};
    }
};

int main()
{
    cout << "Hey champ!";
    int n;
    cin >> n;
    cout << n;
    return 0;
}