// This is template generated by CPCLI [https://github.com/ericliclair/cpcli]
// Problem Link: [https://codeforces.com/problemset/problem/116/A]
#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef vector<int> vi;
typedef vector<vector<int>> vvi;

int main()
{
    int n;
    cin >> n;
    int capacity = 0;
    int maxCap = 0;
    for (int i = 0; i < n; i++)
    {
        int leave, board;
        cin >> leave >> board;
        capacity = capacity - leave + board;
        maxCap = max(maxCap, capacity);
    }
    cout << maxCap;
    return 0;
}