// This is template generated by CPCLI [https://github.com/ericliclair/cpcli]
// problem link [https://cses.fi/problemset/task/1617]

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef vector<int> vi;
typedef vector<vector<int>> vvi;

ll mod = 1e9 + 7;

ll powerLL(ll x, ll n)
{
    ll result = 1;
    while (n)
    {
        if (n & 1)
            result = result * x % mod;
        n = n / 2;
        x = x * x % mod;
    }
    return result;
}

ll bitStrings(ll &n)
{
    return powerLL(2, n) % mod;
}

int main()
{
    ll n;
    cin >> n;
    cout << bitStrings(n) << endl;
    return 0;
}